"""Enumerations for Nodal Sentinel financial domain, exceptions, and audit tracking."""
from enum import Enum


class PaymentStatus(str, Enum):
    AUTHORIZED = "AUTHORIZED"
    CAPTURED = "CAPTURED"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED"
    DISPUTED = "DISPUTED"


class PaymentMethod(str, Enum):
    CARD = "CARD"
    UPI = "UPI"
    NETBANKING = "NETBANKING"
    WALLET = "WALLET"


class CardType(str, Enum):
    CREDIT = "CREDIT"
    DEBIT = "DEBIT"


class DisputeEventType(str, Enum):
    REFUND = "REFUND"
    REVERSAL = "REVERSAL"
    CHARGEBACK = "CHARGEBACK"
    CHARGEBACK_REVERSAL = "CHARGEBACK_REVERSAL"


class LedgerEntryType(str, Enum):
    SETTLEMENT_CREDIT = "SETTLEMENT_CREDIT"
    SETTLEMENT_DEBIT = "SETTLEMENT_DEBIT"
    DISPUTE_HOLD = "DISPUTE_HOLD"
    REFUND_DEBIT = "REFUND_DEBIT"
    FEE_DEBIT = "FEE_DEBIT"
    REVERSAL = "REVERSAL"
    ADJUSTMENT = "ADJUSTMENT"


class ExceptionType(str, Enum):
    GHOST_SETTLEMENT = "GHOST_SETTLEMENT"
    REFUND_CHARGEBACK_DOUBLE_DIP = "REFUND_CHARGEBACK_DOUBLE_DIP"
    SETTLEMENT_SLA_BREACH = "SETTLEMENT_SLA_BREACH"
    PARTIAL_SETTLEMENT = "PARTIAL_SETTLEMENT"
    MISSING_UNALLOCATED_SETTLEMENT = "MISSING_UNALLOCATED_SETTLEMENT"
    LEGITIMATE_TIMING_EXCEPTION = "LEGITIMATE_TIMING_EXCEPTION"
    UNKNOWN_DISCREPANCY = "UNKNOWN_DISCREPANCY"


class ExceptionSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ExceptionState(str, Enum):
    DETECTED = "DETECTED"
    INVESTIGATING = "INVESTIGATING"
    DIAGNOSED = "DIAGNOSED"
    AWAITING_ACTION = "AWAITING_ACTION"
    RESOLVING = "RESOLVING"
    VERIFYING = "VERIFYING"
    VERIFIED_CLOSED = "VERIFIED_CLOSED"
    FAILED_ESCALATED = "FAILED_ESCALATED"


class TransitionActorType(str, Enum):
    SYSTEM = "SYSTEM"
    AI_AGENT = "AI_AGENT"
    FINANCE_CONTROLLER = "FINANCE_CONTROLLER"
    HUMAN = "HUMAN"
    SERVICE = "SERVICE"



class InvestigationStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class RemediationActionType(str, Enum):
    LEDGER_ADJUSTMENT_PROPOSAL = "LEDGER_ADJUSTMENT_PROPOSAL"
    EVIDENCE_DISPUTE_PACKET = "EVIDENCE_DISPUTE_PACKET"
    CLEAR_LEGITIMATE_EXCEPTION = "CLEAR_LEGITIMATE_EXCEPTION"
    APPROVED_RESOLUTION = "APPROVED_RESOLUTION"
    ESCALATE = "ESCALATE"


class RemediationStatus(str, Enum):
    PLANNED = "PLANNED"
    PROPOSED = "PROPOSED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    AWAITING_VERIFICATION = "AWAITING_VERIFICATION"
    CANCELLED = "CANCELLED"


class ApprovalDecision(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"



class VerificationStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"
    PASSED = "PASSED"  # backward compatibility


class VerificationMode(str, Enum):
    AUTOMATED = "AUTOMATED"
    HUMAN_ASSISTED = "HUMAN_ASSISTED"


class VerificationResultStatus(str, Enum):
    PASSED = "PASSED"
    FAILED = "FAILED"


class OrderFulfillmentStatus(str, Enum):
    PENDING = "PENDING"
    FULFILLED = "FULFILLED"
    CANCELLED = "CANCELLED"
    RETURNED = "RETURNED"


class ExposureType(str, Enum):
    DIRECT_FINANCIAL_LOSS = "DIRECT_FINANCIAL_LOSS"
    FUNDS_AT_RISK = "FUNDS_AT_RISK"
    TEMPORARY_LIQUIDITY_IMPACT = "TEMPORARY_LIQUIDITY_IMPACT"
    RECONCILIATION_DISCREPANCY = "RECONCILIATION_DISCREPANCY"
    SLA_DELAY_IMPACT = "SLA_DELAY_IMPACT"
    OPERATIONAL_RISK = "OPERATIONAL_RISK"
    NO_FINANCIAL_EXPOSURE = "NO_FINANCIAL_EXPOSURE"


class MaterialityLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    MATERIAL = "MATERIAL"
    SEVERE = "SEVERE"


class PriorityLevel(str, Enum):
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"


class EscalationRecommendation(str, Enum):
    NO_ESCALATION = "NO_ESCALATION"
    OPERATIONS_REVIEW = "OPERATIONS_REVIEW"
    FINANCE_REVIEW = "FINANCE_REVIEW"
    RISK_REVIEW = "RISK_REVIEW"
    IMMEDIATE_ESCALATION = "IMMEDIATE_ESCALATION"


class PolicyDecisionType(str, Enum):
    ALLOW = "ALLOW"
    ALLOW_WITH_CONDITIONS = "ALLOW_WITH_CONDITIONS"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
    REQUIRE_ESCALATION = "REQUIRE_ESCALATION"
    BLOCK = "BLOCK"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class PolicyActionType(str, Enum):
    NO_ACTION = "NO_ACTION"
    INVESTIGATE = "INVESTIGATE"
    RECONCILE = "RECONCILE"
    ALLOCATE_SETTLEMENT = "ALLOCATE_SETTLEMENT"
    REFUND = "REFUND"
    REVERSE_REFUND = "REVERSE_REFUND"
    RESOLVE_EXCEPTION = "RESOLVE_EXCEPTION"
    ESCALATE = "ESCALATE"
    REQUEST_APPROVAL = "REQUEST_APPROVAL"
    REQUEST_MORE_EVIDENCE = "REQUEST_MORE_EVIDENCE"


class ApprovalRole(str, Enum):
    OPERATIONS = "OPERATIONS"
    FINANCE = "FINANCE"
    RISK = "RISK"
    ADMIN = "ADMIN"


class EscalationLevel(str, Enum):
    NONE = "NONE"
    OPERATIONS = "OPERATIONS"
    FINANCE = "FINANCE"
    RISK = "RISK"
    EXECUTIVE = "EXECUTIVE"


class EvaluationStatus(str, Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class EvaluationMatchStatus(str, Enum):
    TRUE_POSITIVE = "TRUE_POSITIVE"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    FALSE_NEGATIVE = "FALSE_NEGATIVE"
    TYPE_MISMATCH = "TYPE_MISMATCH"
    LEGITIMATE_CORRECT = "LEGITIMATE_CORRECT"
    LEGITIMATE_FALSE_POSITIVE = "LEGITIMATE_FALSE_POSITIVE"


class EvaluationErrorCategory(str, Enum):
    MISSED_EXCEPTION = "MISSED_EXCEPTION"
    FALSE_ALERT = "FALSE_ALERT"
    WRONG_TYPE = "WRONG_TYPE"
    WRONG_ROOT_CAUSE = "WRONG_ROOT_CAUSE"
    WRONG_EXPOSURE = "WRONG_EXPOSURE"
    WRONG_SEVERITY = "WRONG_SEVERITY"
    WRONG_PRIORITY = "WRONG_PRIORITY"
    WRONG_POLICY = "WRONG_POLICY"
    WRONG_REMEDIATION = "WRONG_REMEDIATION"
    WRONG_VERIFICATION = "WRONG_VERIFICATION"
    FALSE_CLOSURE = "FALSE_CLOSURE"
    LEGITIMATE_CASE_CORRUPTION = "LEGITIMATE_CASE_CORRUPTION"


